PRODUCT_CARD = ".produto_lista.MolduraProdutos"
NAME = ".produto_lista_titulo a"
IMAGE = ".produto_lista_imagem img"
LINK = ".produto_lista_imagem a"
BUY_BUTTON = ".produto_lista_botoes__bt"               # first one: "COMPRAR NOVO" / "COMPRAR USADO" / "PRÉ-ENCOMENDAR"
BUY_LABEL = ".produto_lista_botoes__bt_texto"
PRICE = ".produto_lista_botoes__bt_preco"              # price the customer pays
OLD_PRICE = ".produto_desconto_valor"                  # crossed-out price, only when on sale
OUT_OF_STOCK = ".produto_lista_stock_esgotado"              # also used for "Pré-encomenda"; check the text
RELEASE_DATE = ".produto_lista_botoes__bt_vermelho"        # "Lançamento: 15 Outubro 2026" on pre-orders
