-- Project10794 schema (PostgreSQL)
-- Safe to re-run: each table is only created if it does not exist yet.
--
-- Catalogue:   platforms -> games -> game_editions
-- Stores:      stores -> store_products -> price_snapshots   (filled by scrapers)
--              stores -> scrape_runs                         (one row per scraper run)
-- Marketplace: made by Alembic (migrations/, app/models.py)
--
-- Times are UTC, without a time zone (timestamp): the API sends them with a "Z" (db.py).

-- The current time in UTC, once per statement (every row a statement writes gets the same time)
CREATE OR REPLACE FUNCTION utcnow() RETURNS timestamp
    LANGUAGE sql STABLE AS $$ SELECT timezone('utc', statement_timestamp()) $$;

-- Names sorted without case, like SQL Server did ("ABSOLUM" and "Absolum" are the same title, so a
-- game's platforms stay together): Portuguese, accents count, case doesn't. (Hyphens and apostrophes
-- do count here; SQL Server's Windows sorting skipped them.) For display names that are sorted,
-- never searched with LIKE (which this kind of collation restricts)
CREATE COLLATION IF NOT EXISTS pt_ci (provider = icu, locale = 'pt-PT-u-ks-level2', deterministic = false);

-- ============================================================
-- Catalogue
-- ============================================================

CREATE TABLE IF NOT EXISTS platforms (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(20)  NOT NULL UNIQUE,   -- 'PS5', 'Switch2', 'XboxSeries'... (matches app/utils/utils.py)
    name        varchar(100) COLLATE pt_ci NOT NULL,
    sort_order  integer      NOT NULL DEFAULT 100 -- display order in lists and filters
);

-- One row per game per platform, shared by every store and by user listings.
-- Editions (Deluxe, Day One...) are in game_editions, not separate games.
CREATE TABLE IF NOT EXISTS games (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id      integer      NOT NULL REFERENCES platforms(id),
    title            varchar(300) COLLATE pt_ci NOT NULL, -- display name, without edition: "Silent Hill: Townfall"
    normalized_title varchar(300) NOT NULL,     -- ParsedTitle.game_key (core/editions.py), used for matching
    -- The game's English name, shown when the page is in English: IGDB's name (pipeline/igdb.py),
    -- correctable by moderators. "" = looked up, IGDB has none (the store title is shown)
    title_en         varchar(300) NULL,
    -- title corrected by a moderator (a store's typo): the processing and the rematch keep it
    title_fixed      boolean      NOT NULL DEFAULT false,
    image_url        varchar(1000) NULL,
    created_at       timestamp    NOT NULL DEFAULT utcnow(),
    -- A game no store sells, created from IGDB by a user selling a copy (app/services/igdb_game_service.py):
    -- who created it (users.id; no foreign key, the users table is made later by Alembic)
    created_by       integer      NULL,
    -- Game information from IGDB (pipeline/igdb.py); igdb_checked_at is set even when no match was found
    igdb_id          integer      NULL,
    igdb_checked_at  timestamp    NULL,
    summary          text         NULL,          -- in English
    genres           varchar(500) NULL,          -- "Adventure, Shooter"
    publishers       varchar(500) NULL,
    developers       varchar(500) NULL,
    first_release_date date       NULL,
    rating           integer      NULL,          -- IGDB total rating 0-100
    pegi             varchar(10)  NULL,          -- "16"
    cover_image_id   varchar(50)  NULL,
    screenshot_ids   text         NULL,          -- JSON list of IGDB image ids
    -- IGDB trailers: JSON list of {"id": YouTube id, "name": "Trailer"}; NULL = not looked up yet, "[]" = IGDB has none
    video_ids        text         NULL,
    -- IGDB game modes and themes, for the tag filter (app/services/tag_service.py): "Single player,
    -- Co-operative" / "Horror, Survival"; NULL = not looked up yet, "" = IGDB lists none
    game_modes       varchar(500) NULL,
    themes           varchar(500) NULL,
    -- IGDB time to beat (pipeline/igdb.py, fill_time_to_beat): seconds to finish rushing / normally /
    -- 100%, and how many players gave times; ttb_checked_at set even when IGDB has none
    ttb_hastily      integer      NULL,
    ttb_normally     integer      NULL,
    ttb_completely   integer      NULL,
    ttb_count        integer      NULL,
    ttb_checked_at   timestamp    NULL,
    CONSTRAINT uq_games_title_platform UNIQUE (normalized_title, platform_id)
);
-- Columns added after a database was made (CREATE TABLE IF NOT EXISTS leaves it as it was)
ALTER TABLE games ADD COLUMN IF NOT EXISTS title_fixed boolean NOT NULL DEFAULT false;

-- Editions of a game: Standard, Deluxe, Day One, Collector's, Game Key Card...
CREATE TABLE IF NOT EXISTS game_editions (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id      integer      NOT NULL REFERENCES games(id),
    edition_key  varchar(200) NOT NULL,         -- ParsedTitle.edition_key: "" = standard, "deluxe", "|Game Key Card"
    name         varchar(200) COLLATE pt_ci NOT NULL, -- display name: "Standard", "Deluxe Edition"
    created_at   timestamp    NOT NULL DEFAULT utcnow(),
    CONSTRAINT uq_game_editions UNIQUE (game_id, edition_key)
);

-- ============================================================
-- Stores and scraped data
-- ============================================================

CREATE TABLE IF NOT EXISTS stores (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        varchar(50)  NOT NULL UNIQUE,  -- matches the "store" value the scrapers emit
    name        varchar(100) COLLATE pt_ci NOT NULL,
    base_url    varchar(500) NOT NULL,
    is_active   boolean      NOT NULL DEFAULT true, -- turn a scraper off without deleting its history
    created_at  timestamp    NOT NULL DEFAULT utcnow()
);

-- One row per listing on a store's website. Updated in place on every scrape.
CREATE TABLE IF NOT EXISTS store_products (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id       integer       NOT NULL REFERENCES stores(id),
    game_id        integer       NULL REFERENCES games(id), -- NULL until the matcher links it
    edition_id     integer       NULL REFERENCES game_editions(id),
    platform_id    integer       NULL REFERENCES platforms(id),
    external_name  varchar(300)  NOT NULL,      -- name exactly as the store shows it
    url            varchar(800)  NOT NULL,
    image_url      varchar(1000) NULL,
    condition      varchar(10)   NOT NULL DEFAULT 'new',
    is_preorder    boolean       NOT NULL DEFAULT false,
    release_date   date          NULL,          -- as the store announces it; 31/12 often means "this year, no date yet"
    release_date_checked_at timestamp NULL,     -- last time the date was read from the product page (Press Start)
    description    text          NULL,          -- the store's product description, as plain text
    details        text          NULL,          -- JSON {"Editora": "...", "Género": "..."} from the store's data sheet
    details_checked_at timestamp NULL,          -- when the product page was read (read once)
    -- The store's photos of a product besides the cover (special editions: what's in the box),
    -- JSON list of URLs, read with the description
    image_urls     text          NULL,
    first_seen_at  timestamp     NOT NULL DEFAULT utcnow(),
    last_seen_at   timestamp     NOT NULL DEFAULT utcnow(),
    is_active      boolean       NOT NULL DEFAULT true, -- false when it disappears from the store
    -- condition is part of the key: a store can sell new and used copies on the same page
    CONSTRAINT uq_store_products_url UNIQUE (store_id, url, condition),
    CONSTRAINT ck_store_products_condition CHECK (condition IN ('new', 'used'))
);

-- Price history: a new row only when price, old price or stock changes.
-- store_products.last_seen_at says when the latest price was last confirmed.
CREATE TABLE IF NOT EXISTS price_snapshots (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_product_id  integer       NOT NULL REFERENCES store_products(id),
    price             numeric(10,2) NOT NULL,     -- price the customer pays now
    old_price         numeric(10,2) NULL,         -- crossed-out price when on sale
    in_stock          boolean       NOT NULL,
    scraped_at        timestamp     NOT NULL DEFAULT utcnow()
);

-- Lets you see when a store's scraper breaks (e.g. the site changed its HTML).
CREATE TABLE IF NOT EXISTS scrape_runs (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id        integer     NOT NULL REFERENCES stores(id),
    started_at      timestamp   NOT NULL DEFAULT utcnow(),
    finished_at     timestamp   NULL,
    status          varchar(10) NOT NULL DEFAULT 'running',
    products_found  integer     NULL,
    error_message   text        NULL,
    -- warning: far fewer products than last time, missing products were not deactivated
    CONSTRAINT ck_scrape_runs_status CHECK (status IN ('running', 'success', 'warning', 'failed'))
);

-- Games / editions merged into another by pipeline/rematch.py: old links (/game/<id>) and
-- wishes saved in browsers (edition ids) are sent to the one that replaced them
CREATE TABLE IF NOT EXISTS merged_ids (
    kind      varchar(10) NOT NULL CHECK (kind IN ('game', 'edition')),
    old_id    integer     NOT NULL,
    new_id    integer     NOT NULL,
    merged_at timestamp   NOT NULL DEFAULT utcnow(),
    CONSTRAINT pk_merged_ids PRIMARY KEY (kind, old_id)
);

-- ============================================================
-- Marketplace (users, listings, photos, conversations, messages, ratings, collection, reviews):
-- made by Alembic from app/models.py (migrations/); python -m database.setup runs both
-- ============================================================
