PRODUCT_CARD = "article.product-miniature.js-product-miniature"  
NAME = ".product-title a"
SALE = ".product-price-and-shipping .regular-price"
PRICE = ".product-price-and-shipping .price"
LINK = "a.thumbnail.product-thumbnail"
STOCK = ".circle-semaphore"
DISCOUNT = ".product-price-and-shipping.has_discount"